spring.application.name=investigation-service
server.port=9000
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/investigation_service?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:10092412}
spring.jpa.hibernate.ddl-auto=update

# Swagger configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

jwt.public-key-location=keys/public.pem