spring.application.name=${SPRING_APPLICATION_NAME}

internal.api-key=${INTERNAL_API_KEY}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=${DB_DIALECT}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=${SERVER_PORT:8080}

spring.kafka.bootstrap-servers=${KAFKA_HOST}
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.kafka.consumer.group-id=evidence-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.docker.compose.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
